name: geodesy
description: A Dart library for geodesic and trigonometric calculations working with points and paths
version: 0.10.2
homepage: https://github.com/wingkwong/geodesy

environment:
  sdk: ">=2.17.0 <3.0.0"

dependencies:
  latlong2: ^0.8.2

dev_dependencies:
  lints: ^2.0.0
  test: ^1.16.8
